language: node_js
node_js:
- '8'
install:
- npm i -g yarn && yarn
before_deploy:
- gem install aws-sdk-resources
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAIRXCZFNHF6FME4PQ
  secret_access_key:
    secure: NwxvaCBTpMSuW/ygyuYuXS5gSDrn/Dfmmr0SWAgMWdj3/4axjKNvVqHxMolutiljFAlkqm40kdCYAHDandSUHLIJVIE1f2Zkrg+S6YqdD32OlJaXdBaLwLJ6Fvw37K4XEV47GjjiDsHzxyMa5N256l93ECt7lWNHqIkG9+PLPLc5IT6Ppd/yrPZVZw3fwX6pMyvx+A0zgVTEC8nPESRIJ3xcN5Ak3B5tKbpxJ3x0PP9HR1wXm6WqxsoT6DRHlYOnYGGes1UJXweW6dVpRw053a3myoDWPtemxlXr77bVridTdrZEZGB6PnAmTzJHE24opmAtP2Tfm7uUrbCbDjZbC82/VgRH1vDXus3eoN9ZnnQCppRwQ/FpjNTuMyiuILDy2tM7wMleUBAzngnbi5USSg8C2Z4RfJ+A9GJcuET7Bk4uO3IR2fryqVQpwkqlHYQIk7ZibWPkCzzJxUHrKrmIXSCc6zZqp+HP+Xv3iuEMDFJQCeSIZQNGtbyM8NsfLlO+ACzMQkkLdXQLdYvMPckRlz+g8VftIwwWiHh34a8O10833Ui8iS2cXURo1e//Hpyp+MKJ7qb+qOB4f8Rqsq3+2PN0N9WMhswo5stVC8ZUdAU5yxBN98AaBsDoaFRIlNaIhsJkIDis+WljplrzEUXT8zSFz+r/S8+Jgipjy5/kqoY=
  bucket: spafrol
  acl: public_read
  on:
    repo: frolmr/spa_frontend
