language: node_js
node_js:
- '7'
install:
- npm i -g yarn && yarn
before_deploy:
- yarn build
deploy:
  provider: s3
  access_key_id:
    secure: azjciCcW23Yqrv2yXUuAvuNBImJgKuk1L+YWhJ44UJ4gFIWk7SL+slHyMIYomsXJ+tflB7b0G0jdqfaiAMGrGZxlWm15wpBIePkfw0tLMyGFatqhaFUqCQyvS0vQJ5KX0JGZV1O3xhN5zECDtRdZN4y8cAd6S4QYosaoOiXksPHxR0iNV2aV1stMI75kPMwB4BLbt8ByEzme23z+SC0IUeAzEyf3BSRuIUy26vxEA8GkZGxQwZbGlAAJUk3SbTXt6SkSKMPoDQFdzPrC6pd0c2+7peMUCDj8fctxRMBAELcErQlv25HnI5SW3l4HMjid6X713gYuDD5nuDGxfBJg1LjTxVI+hh8fFZbVKZUUQFngIzIQ4X5uixOhQ8FdPM7WtqQUr8Hxw3QrA4iiF0k4bBEGvvsfo07mGT9aReHMoPKAsbL6YityEMth4VLFeVV78FesgQKFkq8XMGyGmwhAZDjkbJoKVAemiTMRjvh/S527NopOHDSRCyrO2AxhaVv/Dn7OMywHgXuR99NXMMLTVc0ZZ+KuddRklt95E/QL7cMXUreJn1GPOnx0CvGPyQrhfoPgxTezC1YjdEvhr3Bvh2ZiyZWc2+lQtWdmXRtyXFuwOGWT/F7pRDEgKxTSxoMdy1jtzUXlcTVwZkGc10NAh+ly3IJ8yESb8pMLHlFO/jo=
  secret_access_key:
    secure: HVn+XdH1nM8GonX7z9RKGzh5ZttNJnR/EazMGrLZR1yijehki+yeJga+6cZiKKME1h4cd8S25VaDiAK+DKaySybY97ZYLFvfUuy7I+wBYqkalZS/sNtAaY3nbJJwNV2gc5mlcEXM/fNhDutbVMDxO3g/z5+Vk2Xt0zviadOeQAogBzA2D+sLtMKRsE4t3wcuvINeURi2gSOFS18jzrSX+wXKyFQD4aD8sraZkIKy8RnE3JhwLKHl1CJuZp7p2QFguCs1Eq7nLTZdS93pRiVvjF87hXzFUNtNlxLlbKwuRKFXCXgi717lv3Nn15hVXOFihzJMyQ/Rs/fPrtBy51DRzF4EDnsmx1rEwaVpAFvW0MTZPGu4BVI8AWwXLBMBu5pEwt4ieU1L418KHqbszs/C2bDo8qDP3as6KuXiPBpyU7HveUdnOidtVG92lXxLksdOFRmJFoocNpXyOR33uclUVUsjRuYydeTy70ES5jXfMJh6+H3oXmaJBPVZK+LTe2dIq86UnNSd+ZupmJJ/wmwj6I5aOTMsY48ZouaeoQW59mRK3dXnX+Nj/g92J0V2GccBu3iqtugoGgIjoBeZvpSq8IPTI4v4yVL/+x+4pZ8/Y8eow/ajXHQ6BkbRopZjcZ1GSA0olZUnmjnrU0XQ4W9+kmDE3DMIrzvUdGRjXgalwqE=
  bucket: spafrol
  skip_cleanup: true
