export default {
  'en': {
      "nav.homeLink": "Home",
      "nav.loginLink": "Login",
      "nav.profileLink": "Profile",
      "nav.searchButton": "Search",
      "home.welcomeMessage": "To see the posts please login first",
      "login.email": "Email",
      "login.password": "Password",
      "login.submit": "Login",
      "postForm.name": "Name",
      "postForm.title": "Title",
      "postForm.url": "Image URL",
      "postForm.body": "Body",
      "postForm.submit": "Post",
      "postButtons.show": "Show post",
      "postButtons.del": "Delete post",
      "postpage.user": "User",
      "postpage.title": "Title",
      "postpage.body": "Body"
  },
  'ru': {
      "nav.homeLink": "Главная",
      "nav.loginLink": "Войти",
      "nav.profileLink": "Профиль",
      "nav.searchButton": "Найти",
      "home.welcomeMessage": "Войдите, чтобы увидеть посты",
      "login.email": "Email",
      "login.password": "Пароль",
      "login.submit": "Войти",
      "postForm.name": "Имя",
      "postForm.title": "Заголовок",
      "postForm.url": "Ссылка на картинку",
      "postForm.body": "Текст",
      "postForm.submit": "Запостить",
      "postButtons.show": "Показать пост",
      "postButtons.del": "Удалить пост",
      "postpage.user": "Пользователь",
      "postpage.title": "Заголовок",
      "postpage.body": "Текст"
  }
}
